# Generated by Django 2.2 on 2021-02-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20210201_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='project_app.User'),
        ),
    ]
